# Generated by Django 4.0.6 on 2022-07-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
