# Generated by Django 4.0.6 on 2022-08-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_task_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteImages',
        ),
    ]
